// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listBooksAfterCursor = `-- name: ListBooksAfterCursor :many
SELECT id, isbn, title, author, publisher, published_date, thumbnail_url, status, created_at, updated_at
FROM books
WHERE (created_at < $1::TIMESTAMPTZ)
   OR (created_at = $1::TIMESTAMPTZ AND id < $2::UUID)
ORDER BY created_at DESC, id DESC
LIMIT $3::INT
`

type ListBooksAfterCursorParams struct {
	CursorCreatedAt pgtype.Timestamptz
	CursorID        uuid.UUID
	LimitCount      int32
}

func (q *Queries) ListBooksAfterCursor(ctx context.Context, arg ListBooksAfterCursorParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooksAfterCursor, arg.CursorCreatedAt, arg.CursorID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Publisher,
			&i.PublishedDate,
			&i.ThumbnailUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksFirst = `-- name: ListBooksFirst :many
SELECT id, isbn, title, author, publisher, published_date, thumbnail_url, status, created_at, updated_at
FROM books
ORDER BY created_at DESC, id DESC
LIMIT $1::INT
`

func (q *Queries) ListBooksFirst(ctx context.Context, limitCount int32) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooksFirst, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Publisher,
			&i.PublishedDate,
			&i.ThumbnailUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
