// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BookStatus string

const (
	BookStatusUnread  BookStatus = "unread"
	BookStatusReading BookStatus = "reading"
	BookStatusRead    BookStatus = "read"
	BookStatusLent    BookStatus = "lent"
)

func (e *BookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookStatus(s)
	case string:
		*e = BookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookStatus: %T", src)
	}
	return nil
}

type NullBookStatus struct {
	BookStatus BookStatus
	Valid      bool // Valid is true if BookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookStatus), nil
}

type Book struct {
	ID            uuid.UUID
	Isbn          string
	Title         string
	Author        *string
	Publisher     *string
	PublishedDate pgtype.Date
	ThumbnailUrl  *string
	Status        BookStatus
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
